"""
FSM states and common UI texts.
"""

STATE_IDLE = "IDLE"
STATE_CHOOSING_FOOD = "CHOOSING_FOOD"
STATE_SET_CUTLERY = "SETTING_CUTLERY"
STATE_SET_EXTRA_SET = "SETTING_EXTRA_SET"
STATE_SET_ADDRESS = "SETTING_ADDRESS"
STATE_SET_PHONE = "SETTING_PHONE"
STATE_SET_PAYMENT_METHOD = "SETTING_PAYMENT_METHOD"
STATE_SET_PAYMENT_TRANSFER_TIMING = "SETTING_PAYMENT_TRANSFER_TIMING"
STATE_CONFIRM_ORDER = "CONFIRM_ORDER"

STATE_CONTACT_ADMIN = "CONTACT_ADMIN"
STATE_WAITING_FOR_CHECK = "WAITING_FOR_CHECK"
STATE_SET_CUTLERY_CUSTOM = "SETTING_CUTLERY_CUSTOM"
STATE_PREORDER_CONFIRM = "PREORDER_CONFIRM"
STATE_SET_ORDER_TIME = "SETTING_ORDER_TIME"

BACK_TEXT = "⬅ Назад"
CANCEL_ORDER_TEXT = "❌ Отменить заказ"
MENU_TEXT = "🏠 В главное меню"
CONTACT_ADMIN_TEXT = "👨‍💬 Задать вопрос"
ADMIN_MENU_TEXT = "🛠 Меню оператора"
ADMIN_TO_USER_MENU_TEXT = "👤 Обычное меню"

